### ISSUE TITLE
How to create automation ?

### ISSUE THREAD

**Issue by Lhemamou** [yyrkoon94/lovelace-idf-mobilite#14]
Hey :)

Thanks for the card, it's really amazing. it's working really well here ! I was just asking myself if we can create specific automation with the sensor saved ? (e.g. if my bus will arrive in 5mn, ping me on my phone, etc).

Again, it's an amazing work !!

**Comment by yyrkoon94** [comment]
Hello !

Thanks for your comments ;) Unfortunately, the card doesn't create sensors so you can't create automations :(
