### ISSUE TITLE
how to monitore specifique bus ?

### ISSUE THREAD

**Issue by mcarbonneaux** [yyrkoon94/lovelace-idf-mobilite#19]
i've bus line where i live that have two path (primary and secondary)... i whant to monitor only one path!
how to do that ?

**Comment by yyrkoon94** [comment]
Hello @mcarbonneaux,

You can simply use line filtering.

**Comment by mcarbonneaux** [comment]
my problem is to find the line number corresponding to the primary path and secondary path in the [idf mobility](https://data.iledefrance-mobilites.fr/explore/dataset/arrets/custom/), i don't know how to find it.

**Comment by mcarbonneaux** [comment]
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/8479023/5593f97e-11c7-4072-ae75-5a0e34e275f8)
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/8479023/55faae6e-fbfd-49f7-962d-0636acb128d1)

how to find the primary for exemple in idf mobility reference site ?

**Comment by yyrkoon94** [comment]
Hi @mcarbonneaux,

Not sure to understand .... you have a toggle button in the configuration page :

<img width="1035" alt="Capture d’écran 2024-01-18 à 09 16 16" src="https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/128692411/908650f4-43ab-4ba4-9c19-ac1e3334ef85">

And then you have the line id for filtering :

<img width="1026" alt="Capture d’écran 2024-01-18 à 09 16 24" src="https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/128692411/8e839ef8-5edb-47c3-87f2-3b548c1aac78">

Let me know ;)

**Comment by mcarbonneaux** [comment]
ok i found that...
in fact i've not understanded because the destination are numeric (and not corresponding with somefing on the bus): 
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/8479023/70ee8d43-374f-453a-9662-cada85bba100)
