### ISSUE TITLE
Issue on activating Messages sensor

### ISSUE THREAD

**Issue by Soicnarf** [yyrkoon94/lovelace-idf-mobilite#2]
Hello,
first thank you very much for your work this is super great !!!
I may have found a bug when I tried to add a Messages sensor to the display.
My Message sensor is the following:
- platform: rest
    name: messages_RERD_aller
    unique_id: bbbc536g
    resource: https://prim.iledefrance-mobilites.fr/marketplace/general-message
    method: GET
    params:
      StopPointRef: "STIF:StopArea:SP:41366:"            
      LineRef: "STIF:Line::C01728:"                      
    headers:
      apiKey: !secret PRIM_APIKEY                           
    scan_interval: 3600                                       
    timeout: 30
    value_template: "OK"
    json_attributes:
      - Siri

When I include it in the lovelace card, I have no more trains schedule nor line messages.
I tried to comment out the LineRef, without any effect.
(please note that the scan_interval: 3600 is because I'm updating the sensor with HA update entity service, I tried to remove completly the scan_interval but it seems to fall back on 1 minute update)

Thanks !
++
F.

**Comment by yyrkoon94** [comment]
Hi,

When I try the same stop point I got messages an no display issue. But it looks like the line is a TER :
STIF:StopPoint:Q:41366: | Gare de Combs la Ville Quincy | STIF:Line::C01728: | TER Centre - Val de Loire
You named your sensor RERD_aller, so I supposed you want messages on RER D but you choose a TER ... are you sure ?

Anyway, it works, so probably the issue come from another part of the lovelace card. 
What other sensor do you use in your card ?

**Comment by Soicnarf** [comment]
Ok , I may have not restarted HA when I disabled the LineRef in the Message sensor.
So all is fine, it's working now !
Many thanks

**Comment by yyrkoon94** [comment]
Ok perfect ! I'm looking for your other issue ;)
