### ISSUE TITLE
bug: no direction on the cards!?

### ISSUE THREAD

**Issue by mcarbonneaux** [yyrkoon94/lovelace-idf-mobilite#23]
in my case (STIF:StopArea:SP:54156:) we have only the name of the bus line (3801) and not the direction (mairie de montlignon) of the path :
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/8479023/88553d23-228b-45a3-83ca-2cfde95b5342)

**Comment by yyrkoon94** [comment]
Hello,

Yes sometimes you have an id, sometimes a direction. You can use both for filtering ;)

**Comment by mcarbonneaux** [comment]
there no way to have direction in place off id ? 
elseway by add name configurability ?
