### ISSUE TITLE
Issue with API, wrong reference or display issue ?

### ISSUE THREAD

**Issue by gtedavid** [yyrkoon94/lovelace-idf-mobilite#25]
Hi there,

I noticed this while fideling around with the API for home assistant and your Lovelace Card (which, thank you for it by the way).

Here is what you'd expect on the RER B for all stations.
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/60758334/3a3899b7-5080-42a8-ad60-2bf6505d8469)

Unfortunately, I noticed that wasn't the case for a station in the south of the line.
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/60758334/d51257e0-0379-4491-97d1-e58c57953a3a)
MonitoringRef: "STIF:StopArea:SP:70033:"

I've tried for several different stations in the south and I get different results depending if I try the area or station reference.
I've contacted IDFM through the site to see what they can see on their side.

**Comment by pwagner-psee** [comment]
It's not that this specific StopArea deserves only some trains in one direction? What do you mean that you're getting different results?

**Comment by gtedavid** [comment]
Nevermind, seemed to have been a glitch with the api
