### ISSUE TITLE
Update time UTC instead of local time

### ISSUE THREAD

**Issue by yyrkoon94** [yyrkoon94/lovelace-idf-mobilite#27]
The update time is in UTC format instead of local format.

**Comment by Ninic0c0** [comment]
Hey, thanks for the work ! Any update on this issue ?

**Comment by yyrkoon94** [comment]
Hello,

First of all, thank you ;)

Yes the issue is fixed, I've just create a new release (v0.2.1)

**Comment by Ninic0c0** [comment]
I confrm v0.2.1 fix the issue. Thanks 👍
