### ISSUE TITLE
Bus not displayed if 'DestinationDisplay' is empty even if 'DestinationName' is set

### ISSUE THREAD

**Issue by cht0m** [yyrkoon94/lovelace-idf-mobilite#32]
I can't get any information displayed in the card for several bus lines that I'm interrested in. I noticed that it occurs when there is no DestinationDisplay:

      DestinationDisplay: []

If I manually edit my sensor and add a value, then the buses will be displayed.

I suppose that this was expected behavior as "DestinationDisplay" is empty but I also noticed that the field 'DestinationName' was properly filled.
Would it make sense to use the value of DestinationName when DestinationDisplay is missing?

Data to reproduce the issue (same issue with most of the bus lines in that area):
STIF:StopPoint:Q:411956:
STIF:Line::C02264:

Thanks for your work, I really appreciate this card.

**Comment by yyrkoon94** [comment]
Hi @cht0m,

Seems a good idea, let me check ;)
