### ISSUE TITLE
Data issue

### ISSUE THREAD

**Issue by ziram78** [yyrkoon94/lovelace-idf-mobilite#33]
Hello 
it seems to me that I've done the configuration correctly, on the PRIM interface I see that I'm generating requests but my lovelace card remains empty.

- platform: rest
  name: andresy_transport
  unique_id: xxxxxxx
  resource: https://prim.iledefrance-mobilites.fr/marketplace/stop-monitoring
  method: GET
  params:
    MonitoringRef: "STIF:StopArea:SP:47916:"
  headers:
    apiKey: "xxxxxxxx"
  scan_interval: 60
  timeout: 30
  value_template: "OK"

![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/62407058/d5620ebc-dbe9-40c7-8d3b-dd95e7b600fb)

**Comment by yyrkoon94** [comment]
Hi @ziram78,

My first test is that your stop (47916) get no data from PRIM API. Let me know where is this stop so I can check more precisely what happen.

**Comment by ziram78** [comment]
Hi @yyrkoon94, thank you for your keep reply.

I tried to change it by the Saint Lazare (71370) rail station and nothing works.
and where i live andresy (65542)

![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/62407058/48efbd85-8b0b-4b45-a78a-b19ebfbf4bbd)

Best,

**Comment by yyrkoon94** [comment]
Hi @ziram78,

Found your problem ;) 
You forget to add (in your configuration.yaml):
    json_attributes:
      - Siri

**Comment by ziram78** [comment]
Yes great thank you for your help and for the work you have done.

Last questions : 

1. **can you explain me thoses lines** 

  json_attributes:
    - Siri

2. **what is unique_id**

3. if i want to add other sensors :

I just have to copy past and change the Stoparea ID ?

**Comment by yyrkoon94** [comment]
Cool !
So :
1/ It's use from REST sensor to get a specif node from the json as an attribute of the sensor. So the first test I made is to check if I have an attribute called "Siri". So without that, the card will not work
2/ unique_id is not mandatory but is usefull if you want to modify the esnsor from the HA interface (changing name, ...). It's a UUID that you can generate here for example : https://www.uuidgenerator.net/version4
3/ If you want to add more line on different stops just create a second sensor (duplicate everything) with a different name and different unique_id and of course a different MonitoringRef (for exemple, for debugging I have more than 10 different lines ;)

Enjoy !

**Comment by ziram78** [comment]
Yes great, it works nicely. My last question is it possible to retreive the dock.

**Comment by yyrkoon94** [comment]
Hmmm I don't think so.
