### ISSUE TITLE
Issue with non ratp lines import

### ISSUE THREAD

**Issue by Zolued** [yyrkoon94/lovelace-idf-mobilite#4]
Hello,

I just installed this plugin (version 0.1.6), I configured the configuration.yaml and when I try to add the custom card to my dashboard, it says 
`Custom element doesn't exist: idf-mobilite-card.`

I checked the browser console, I have this message
`Uncaught SyntaxError: missing ) after argument list[idf-mobilite.js:9:76]`

If I go back to version 0.1.4, before you added the non RATP lines, the custom card works.

Thanks

**Comment by yyrkoon94** [comment]
Hello ;)

Which browser do you used ?

I don't have this problem with Chrome, Edge or Safari ...

**Comment by Zolued** [comment]
Firefox

**Comment by yyrkoon94** [comment]
Ok, got the same issue ;) 

Let me check ...

**Comment by yyrkoon94** [comment]
Fixed in the 0.1.7 release.

**Comment by Zolued** [comment]
Great thanks
