### ISSUE TITLE
icon broken on 0.1.9

### ISSUE THREAD

**Issue by tikifarm** [yyrkoon94/lovelace-idf-mobilite#6]
damn, im making you work hard today lol, sorry

![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/42776726/ffbad3de-fb20-4f14-be94-a561749ccb83)

soo.. fun fact or not so fun fact, 1.9 broke the icons for T10 🤣 
(it might be only me ? i tried clearing cache issue remains)

**Comment by yyrkoon94** [comment]
Com'on .... it's fxed ([v0.1.10](https://github.com/yyrkoon94/lovelace-idf-mobilite/tree/v0.1.10)) ;)

**Comment by tikifarm** [comment]
fixed!
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/42776726/3bee1948-fda3-4091-ac02-cc880f4b23b7)

not broken!
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/42776726/b687b662-8ac8-4a67-9fd7-426ca9ef2ef3)

cya tomorrow, il probably find something else /s 
jokes aside, thank you for the great work, its thanks to devs like we this community thrives :D
