### ISSUE TITLE
missing icon...

### ISSUE THREAD

**Issue by mcarbonneaux** [yyrkoon94/lovelace-idf-mobilite#7]
awesome card !!!
i'm using v0.1.10, and i have icons that are missing:

in the html they use rail.png in place of train.png...
i've try to modify the page to check (in my screen shot you can see the first icon with the train.png and the seconds with rail.png)
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/8479023/2c4633db-37e2-4451-96b4-7ae49927c737)

**Comment by yyrkoon94** [comment]
Hi,

Can you give me you're configuration to reproduce the issue please ? (just the MonitoringRef)

**Comment by mcarbonneaux** [comment]
MonitoringRef: "STIF:StopArea:SP:65669:"

**Comment by wgrs33** [comment]
Hey! Honestly I find it easier to read the data when using Bus lineType even for the RER/SNCF, but the missing icons are annoying.

**Comment by yyrkoon94** [comment]
Hello,

Icon added in the next release.

**Comment by mcarbonneaux** [comment]
it's working now
